class HandledException(Exception):
    # Usage: HandledException(ValueError("Raise Exception"))
    pass
